/**
 * JSForge - 报告生成工具
 */

import { z } from 'zod';
import { tool } from '@langchain/core/tools';
import { writeFileSync } from 'fs';
import { getReportPath } from './utils.js';

/**
 * 生成分析报告
 */
export const generateReport = tool(
  async ({ title, content, filename }) => {
    const report = `# ${title}

${content}

---
*Generated by JSForge*
`;
    const savePath = getReportPath(filename);
    writeFileSync(savePath, report, 'utf-8');
    console.log('[report] saved to:', savePath);
    return JSON.stringify({ success: true, filePath: savePath });
  },
  {
    name: 'generate_report',
    description: '生成 Markdown 分析报告，自动保存到 output/reports 目录',
    schema: z.object({
      title: z.string().describe('报告标题'),
      content: z.string().describe('报告内容'),
      filename: z.string().optional().describe('文件名（可选，默认自动生成）'),
    }),
  }
);

export const reportTools = [generateReport];
